title: "5ISS project : Towards context-aware IoT systems"
description: "Is it possible to infer information about a device's whereabouts based on its connectivity status ? Let's find out !"
show_downloads: "true"
theme: jekyll-theme-slate
